### ISSUE TITLE
Parse Dashboard can only be remotely accessed via HTTPS

### ISSUE THREAD

**Issue by pewh** [yongjhih/docker-parse-dashboard#4]
I want to test docker parse dashboard on localhost. And when I navigate to `http://<docker-ip>:4040`, I get this error: `Parse Dashboard can only be remotely accessed via HTTPS`

Edit:
I successfully omit that error message by adding env `PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1` and `SERVER_URL=http://<docker-ip>:1337/parse`. But now I get new error message: `Configure a user to access Parse Dashboard remotely`. So my question is: how to add users via env on Docker?

**Comment by pewh** [comment]
Aha! I add env `USER1`, `USER1_PASSWORD`, and everything is work!

**Comment by mymanga** [comment]
Not working for me. I tried"USER1,USER1_PASSWORD" and also "PARSE_DASHBOARD_USER1, PARSE_DASHBOARD_USER1_PASSWORD"  and also both at the same time.....Dashboard is still asking for user.

Working with Docker toolbox on windows 10. Parse server running OK

**Comment by egorvas** [comment]
@mymanga Did you resolve this problem? I have this issue too...

**Comment by rahimrahman** [comment]
@mymanga @egorvas did you guys get this issue resolved?

**Comment by egorvas** [comment]
@rahimrahman yes, you just need to set PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1 and configure HTTPS connection with nginx-proxy

**Comment by rahimrahman** [comment]
I used `PARSE_DASHBOARD_CONFIG` instead:

```
docker run -d \
            -e PARSE_DASHBOARD_CONFIG='{"apps":[{"appId":"<appid>","serverURL":"<docker-ip>/parse","masterKey":"<masterkey>","appName":"<appname>"}],"users":[{"user":"<username>","pass":"<password>"}]}' \
            -e PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1  \
            -p 4040:4040                      \
            --link parse-server               \
            --name parse-dashboard            \
            yongjhih/parse-dashboard
```

**Comment by manoj-singh-developer** [comment]
The change is

app.use('/parse-dashboard', new ParseDashboard(config.dashboard, { allowInsecureHTTP: true }));

instead of

app.use('/parse-dashboard', ParseDashboard(config.dashboard, true));

you will find this code in index.js
