### ISSUE TITLE
mountpath option

### ISSUE THREAD

**Issue by Murf** [yongjhih/docker-parse-dashboard#5]
per
https://github.com/ParsePlatform/parse-dashboard/commit/089b2ab99e6211c87d68deb2e10b62d56e39c0ff

**Comment by yongjhih** [comment]
Merged 089b2ab . You can update latest image by the following command: `docker pull yongjhih/parse-dashboard`

**Comment by Murf** [comment]
thanks, much appreciated :)

**Comment by katopz** [comment]
@yongjhih And how can I set `MOUNT_PATH` ? 
I try 

```
MOUNT_PATH=parse-dashboard/ docker-compose restart
```

but no luck yet, do I've to get in container and set node env my self?

Thanks

**Comment by yongjhih** [comment]
``` sh
PARSE_MOUNT=/parse-dashboard docker-compose restart
```

**Comment by katopz** [comment]
@yongjhih refer to
- Specify parse-server prefix: `-e PARSE_MOUNT={/parse}`

I think `PARSE_MOUNT` is parse server path isn't it?
May be it's [PARSE_DASHBOARD_MOUNT_PATH](https://github.com/yongjhih/docker-parse-dashboard/blob/master/docker-compose.yml#L20)?

what I want is 
`foo.com/parse` for parse server
`foo.com/parse-dashboard` for dashboard

at the moment `foo.com/parse-dashboard` look like this

![screen shot 2559-05-11 at 10 39 58 pm](https://cloud.githubusercontent.com/assets/97060/15186998/7821e3b4-17c9-11e6-9e79-d45ca59ea7cf.png)

which is wrong and not working for both `PARSE_MOUNT` and `PARSE_DASHBOARD_MOUNT_PATH`

I expected 

```
<script src="bundles/dashboard.bundle.js"></script>
```

or

```
<script src="/parse-dashboard/bundles/dashboard.bundle.js"></script>
```

any hint?

**Comment by katopz** [comment]
Hm.
somehow https://github.com/yongjhih/docker-parse-server/blob/master/docker-compose.yml#L119
didn' t pass through `PARSE_DASHBOARD_MOUNT_PATH` and `PARSE_DASHBOARD_TRUST_PROXY` as defined here  https://github.com/yongjhih/docker-parse-dashboard/blob/master/docker-compose.yml#L19

I think it missing?

**Comment by yongjhih** [comment]
Please follow docker-parse-dashboard/`docker-compose.yml`, i always update it after merged patches.

docker-parse-server is as stack for partner projects, I think it's missing update. Thanks for your report.

ref. https://github.com/yongjhih/docker-parse-server/commit/54e308008e24e5e65cac27f09fbe317ac534ce6c
